package com.ojoclaro.android.agent.command.adapter

enum class CommandAgentIntent {
    READ_VISIBLE_SCREEN,
    SUMMARIZE_VISIBLE_SCREEN,
    EXPLAIN_VISIBLE_SCREEN,
    OPEN_APP,
    PREPARE_MESSAGE,
    CONFIRM_PENDING_ACTION,
    CANCEL_PENDING_ACTION,
    REPEAT_LAST_RESPONSE,
    MODIFY_RESPONSE_SHORTER,
    MODIFY_RESPONSE_MORE_DETAIL,
    CHECK_SCREEN_RISK
}
